In [1]:
import warnings
warnings.filterwarnings(action='ignore') 
%config Completer.use_jedi = False 
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np
import pandas as pd

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
# x => [공부 시간, 과외 시간] 
x = [[2, 3], [4, 3], [6, 4], [8, 6], [10, 7], [12, 8], [14, 9]] # 7행 2열, 2차원
print(x)
print(type(x))

xData = np.array(x)
print(xData)
print(type(xData))

[[2, 3], [4, 3], [6, 4], [8, 6], [10, 7], [12, 8], [14, 9]]
<class 'list'>
[[ 2  3]
 [ 4  3]
 [ 6  4]
 [ 8  6]
 [10  7]
 [12  8]
 [14  9]]
<class 'numpy.ndarray'>


In [3]:
# y => [합격 여부] => 실제값
y = [0, 0, 0, 1, 1, 1, 1] # 1행 7열, 1차원
print(y)
print(type(y))

yData = np.array(y)
print(yData)
print(type(yData))

# reshape(): 넘파이에서 데이터는 그대로 유지한채 배열의 형태(차원)을 변경한다.
# 1행 7열 넘파이 배열 => 7행 1열 넘파이 배열, 2차원
yData = yData.reshape(7,1)
print(yData)

[0, 0, 0, 1, 1, 1, 1]
<class 'list'>
[0 0 0 1 1 1 1]
<class 'numpy.ndarray'>
[[0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]]


xData와 yData를 저장할 placeholder를 만든다.

In [4]:
# placeholder에 넘파이 배열을 대입할 경우 shape 속성을 이용해서 대입될 넘파이 배열의 차원을 지정해야 한다.
# shape=[None, 2] => placeholder에 대입될 넘파이 배열의 행의 개수는 몇개라도 상관없고 열의 개수는 무조건 2개라는 의미이다. 
X = tf.placeholder(dtype=tf.float32, shape=[None, 2]) # xData가 대입될 placeholder
Y = tf.placeholder(dtype=tf.float32, shape=[None, 1]) # yData가 대입될 placeholder

가중치와 y절편을 임의의 값으로 정한다.

In [5]:
a = tf.Variable(tf.random_uniform([2, 1], dtype=tf.float32)) # 난수를 2행 1렬로 발생시킨다.
b = tf.Variable(tf.random_uniform([1], dtype=tf.float32)) # y절편(바이어스), 0 ~ 1 사이의 난수
sess = tf.Session()
sess.run(tf.global_variables_initializer())
print('a = {}, b ={}'.format(sess.run(a), sess.run(b)))
print('a\n', sess.run(a), sep='')
print('b\n', sess.run(b), sep='')
print('a1: {:f}, a2: {:f}, b: {:f}'.format(sess.run(a)[0][0], sess.run(a)[1][0], sess.run(b)[0]))
print('a1: %f, a2: %f, b: %f' % (sess.run(a)[0], sess.run(a)[1], sess.run(b)))

a = [[0.9412844]
 [0.9557828]], b =[0.8786911]
a
[[0.9412844]
 [0.9557828]]
b
[0.8786911]
a1: 0.941284, a2: 0.955783, b: 0.878691
a1: 0.941284, a2: 0.955783, b: 0.878691


시그모이드 방정식, 오차 함수, 경사 하강  

In [6]:
# sigmoid(): tensorflow에서 시그모이드 방정식을 계산한다.
# matmul(): tensorflow에서 행렬의 곱(적)을 계산한다.
# Y = 1 / (1 + np.e ** - (a * x + b))
# y = tf.sigmoid(a1 * x1 + a2 * x2 + b)
y = tf.sigmoid(tf.matmul(X, a) + b) # 시그모이드 방정식, 예측값(Y -> y)
loss = - tf.reduce_mean(Y * tf.log(y) + (1 - Y) * tf.log(1 - y)) # 오차 함수
gradient_descent = tf.train.GradientDescentOptimizer(0.1).minimize(loss) # 경사 하강

sigmoid() 메소드의 실행 결과(y)가 0.5 이상이면 1을 0.5 미만이면 -1을 리턴시킨다.

In [7]:
sess = tf.Session()
# cast(data, dtype): tensorflow에서 데이터(data)를 dtype으로 형변환 한다.
predict = tf.cast(tf.constant([1.9, 2.1]), dtype=tf.int32)
print(sess.run(predict)) # [1 2]
# cast() 메소드는 캐스팅할 데이터가 boolean 타입이면 True는 1로 False는 0으로 형변환 한다.
predict = tf.cast(tf.constant([True, False]), dtype=tf.int32)
print(sess.run(predict)) # [1 0]
predict = tf.cast([0.5 >= 0.5, 0.5 < 0.5], dtype=tf.int32)
print(sess.run(predict)) # [1 0]

[1 2]
[1 0]
[1 0]


sigmoid() 메소드를 실행한 예측값(0 또는 1)을 계산한다.

In [8]:
predict = tf.cast(y >= 0.5, dtype=tf.float32) # 예측값

예측값(predict)과 실제값(Y)이 일치하는 정도(정확도, 정밀도)

In [9]:
sess = tf.Session()
# equal(): tensorflow에서 인수로 지정한 값이 같으면 True, 다르면 
# False를 리턴한다.
print(sess.run(tf.equal(1,1)), sess.run(tf.equal(1,0))) # True False
# equal() 메소드로 예측값과 실제값이 같은가 비교 후 True 또는 False를
# cast() 메소드로 1 또는 0으로 캐스팅하고 평균을 계산한다.
accuracy = tf.reduce_mean(tf.cast(tf.equal(predict, Y), dtype=tf.float32))

True False


In [10]:
sess = tf.Session() 
sess.run(tf.global_variables_initializer())

# 난수에 따라 nan 나올 수 있다. 그 때는 다시 실행하면 된다.
for epoch in range(3001):
    # sess.run([실행할 내용, ...], feed_dict={플레이스홀더 이름: 
    # 플레이스홀더에 저장할 데이터, ...})
    a_, b_, loss_, _, predict_, accuracy_ = sess.run([a, b, loss, 
    gradient_descent, predict, accuracy], feed_dict={X: xData,
                                                     Y: yData})
    if epoch % 300 == 0:
        print('epoch: {:6d}, loss: {:7.4f}, 기울기 a1: {:7.4f}, 기울기 a2: {:7.4f}, y 절편: {:7.4f}'.format(epoch, loss_, a_[0][0], a_[1][0], b_[0]))
        # print('epoch: %6d, loss: %7.4f, 기울기: %7.4f, y 절편: %7.4f'% (epoch, sess.run(loss), sess.run(a), sess.run(b)))
print('실제값\n ', yData, sep='')
print('예상값\n ', predict_, sep='')
print('정확도: {:6.2%}'.format(accuracy_))

epoch:      0, loss:  1.9783, 기울기 a1:  0.3917, 기울기 a2:  0.4572, y 절편:  0.3193
epoch:    300, loss:  0.2613, 기울기 a1:  0.7886, 기울기 a2: -0.5001, y 절편: -2.5202
epoch:    600, loss:  0.1882, 기울기 a1:  0.7943, 기울기 a2: -0.2403, y 절편: -3.9662
epoch:    900, loss:  0.1476, 기울기 a1:  0.7106, 기울기 a2:  0.0760, y 절편: -5.0159
epoch:   1200, loss:  0.1211, 기울기 a1:  0.6119, 기울기 a2:  0.3736, y 절편: -5.8482
epoch:   1500, loss:  0.1025, 기울기 a1:  0.5169, 기울기 a2:  0.6402, y 절편: -6.5396
epoch:   1800, loss:  0.0887, 기울기 a1:  0.4304, 기울기 a2:  0.8760, y 절편: -7.1315
epoch:   2100, loss:  0.0780, 기울기 a1:  0.3533, 기울기 a2:  1.0848, y 절편: -7.6493
epoch:   2400, loss:  0.0697, 기울기 a1:  0.2847, 기울기 a2:  1.2705, y 절편: -8.1095
epoch:   2700, loss:  0.0629, 기울기 a1:  0.2239, 기울기 a2:  1.4367, y 절편: -8.5238
epoch:   3000, loss:  0.0573, 기울기 a1:  0.1696, 기울기 a2:  1.5865, y 절편: -8.9006
실제값
 [[0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]]
예상값
 [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]]
정확도: 100.00%
